name: Docker Image CI
on:
  push:
    branches: [ "master" ]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/jenkins-lab2:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/jenkins-lab2:latest